server:
  port: 8085
spring:
  datasource:
    url: jdbc:mysql://192.168.88.211:3306/management_system?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=CTT
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: lmn
    password: Lmn123456@
mybatis:
  mapper-locations: classpath:com/lmn/demo/dao/mapping/*.xml
